app_code/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app

class Permission:
    FOLLOW = 1 #Students, Teachers
    COMMENT = 2 #Students, Teachers
    MODERATE = 4 #Teachers
    ADMIN = 8 # Admin

class Role(db.Model):
    __tablename__ = 'roles'
    id    = db.Column(db.Integer, primary_key = True)
    rolename  = db.Column(db.String(64), unique= True)
    default = db.Column(db.Boolean, default=False, index = True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role')

    @staticmethod
    def insert_roles():
        roles = {
            'student' : [Permission.FOLLOW, Permission.COMMENT],
            'teacher' : [Permission.FOLLOW, Permission.COMMENT,
            Permission.MODERATE],
            'admin'   : [Permission.MODERATE, Permission.COMMENT,
             Permission.ADMIN]
        }
        default_role = 'Student'
        for r in roles:
            role = Role.query.filter_by(rolename = r).first()
            if role is None:
                role = Role(rolename = r)
            role.reset_permission()
            for perm in roles[r]:
                role.add_permission(perm)
            role.default = (role.rolename == default_role)

    def __init__(self, **kwargs):
        super(Role, self).__init__(**kwargs)
        if self.permissions is None:
            self.permissions = 0

    def __repr__(self):
        return 'Role %r' % self.rolename

    def add_permission(self, perm):
        if not self.has_permission(perm):
            self.permissions += permission
    
    def remove_permission(self, perm):
        if  self.has_permission(perm):
            self.permissions -= permission

    def reset_permission(self):
        self.permissions = 0

    def has_permission(self, perm):
        return self.permissions & perm == perm

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id           = db.Column(db.Integer, primary_key = True)
    role_id      = db.Column(db.Integer,db.ForeignKey('roles.id'))
    username     = db.Column(db.String(64), unique=True, index=True )
    class_number = db.Column(db.SmallInteger)
    pswd_hashed  = db.Column(db.String(128))
    email        = db.Column(db.String(35), unique = True, index = True)
    confirmed    = db.Column(db.Boolean, default = False)
    @property
    def password(self):
        raise AttributeError(' The Password´s attribute is not readable.')

    @password.setter
    def password(self, password):
        self.pswd_hashed = generate_password_hash(password)

    def verify_pswd(self, password):
        return check_password_hash(self.pswd_hashed, password)

    def __repr__(self):
        return 'User %r' % self.username

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm':self.id}).decode('utf-8')
    
    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data =s.loads(token.encode('utf-8'))
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True

    def __init__(self, **kwargs):
        super(User,self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(rolename = 'admin').first()
            if self.role is None:
                self.role = Role.query.filter_by(default =True).first()
    def can(self, perm):
        return self.role is not None and self.role.has_permission(perm)

    def is_admin(self):
        return self.can(Permission.ADMIN)
        
    def is_teacher(self):
        return self.can(Permission.ADMIN)

@login_manager.user_loader
def load_user(u_id):
    return User.query.get(int(u_id))

app_code/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Length, Email

class UserForm(FlaskForm):
    name = StringField('Write here your username:', validators=[DataRequired()])
    submit = SubmitField('Submit')

app_code/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
mail = Mail()
login_manager.login_view = 'auth.login'
def create_app(cfg_name):
    app = Flask(__name__)
    # The config settings from the object of class Config are imported to the app
    app.config.from_object(config[cfg_name])
    config[cfg_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)

    from .auth import auth as auth_Blueprint
    app.register_blueprint(auth_Blueprint, url_prefix='/auth')

    from .main import main as main_Blueprint
    app.register_blueprint(main_Blueprint)

    return app

app_code/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
# the next module importation are in this order to avoid circular dependencies failure.
from . import views, errors

app_code/main/views.py
from flask import Flask, render_template , session, redirect, url_for
from . import main
from .forms import UserForm

#Functions
@main.route('/', methods=['GET', 'POST'])
def index():
    form = UserForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        return redirect(url_for('.index'))
    return render_template('index.html',form = form, user_name = session.get('name'))

@main.route('/user_guide')
def user_guide():
    return render_template('user_guide.html')

@main.route('/aboutus')
def about_us():
    return render_template('about_us.html')

app_code/templates/about_us.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}School API{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>About us</h1>
</div>



{% endblock %}

app_code/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block tittle %} <div class="glyphicon glyphicon-blackboard">My School API</div>{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toogle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span> 
                <span class="icon-bar"></span>     
                <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand" href='/'>My School API</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Homepage</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.user_guide')}}">User Guide</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.about_us')}}">About us</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout')}}">Log out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login')}}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app_code/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}School API{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Welcome to the School API </h1>
</div>
<h3>Tell us which profile fits you better</h3>

<div class="row marketing">
    <div class="col-md-4">
        <h3><span class="glyphicon glyphicon-wrench" style="color:#9e5a8d;"></span>
            <button  class="btn btn-danger btn-lg" type="button">
                <a style="color:#f0ebef;" href="{{ url_for('auth.register', who = 'student')}}">Admin</a>
            </button>            
        </h3>
       <p>Hands on what should be done functionally talking.</p>
    </div>
    <div class="col-md-4">
      <h3><span class="glyphicon glyphicon-blackboard" style="color:#533cb6;"></span>
        <button  class="btn btn-primary btn-lg" type="button">
            <a style="color:#f0ebef;" href="{{ url_for('auth.register', who = 'teacher')}}">Teacher</a>
        </button>        
      </h3>
      <p>Manage your classes, subjects, exams and more.</p>
    </div>
    <div class="col-md-4">
      <h3><span class="glyphicon glyphicon-education" style="color:#47a34f;"></span>
        <button  class="btn btn-success btn-lg" type="button">
            <a style="color:#f0ebef;" href="{{ url_for('auth.register', who = 'student')}}">Student</a>
        </button>    
      </h3>
      <p>Be up to date with your Timetables, exams, homework and more.<br><br><br><br><br><br><br></p>
    </div>
</div>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
  
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="/static/crew_.jpg" style="height: 300px; width: 980px" >
        <div class="carousel-caption">
            <h3>The Crew</h3>
            <p>Right now there is only one person behind all this API</p>
          </div>
      </div>
  
      <div class="item">
        <img src="/static/madrid.jpg" style="height: 300px; width: 980px" >
        <div class="carousel-caption">
            <h3>Where are we?</h3>
            <p>Currently we are in Madrid</p>
          </div>
      </div>
  
      <div class="item">
        <img src="/static/workwith_us.jpg" style="height: 300px; width: 980px" >
        <div class="carousel-caption">
            <h3 style="color:#050505;">Work with us</h3>
            <p style="color:#141414;">We are currently hiring!</p>
          </div>
      </div>
    </div>
  
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

{% endblock %}

app_code/templates/user_guide.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}School API{% endblock %}

{% block page_content %}

{% endblock %}

app_code/templates/user_main.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block tittle %}Main{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Welcome to the Wonderfull API {% if user_name %}{{user_name}}{% else %}Stranger{% endif %}</h1>
</div>
{{ wtf.quick_form(form)}}
{% endblock %}